name: Docker Compose Actions Workflow
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker compose up -d

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify