name: Maven Actions Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_URL_TEST: ${{ secrets.POSTGRES_URL_TEST }}
      POSTGRES_DB_TEST: ${{ secrets.POSTGRES_DB_TEST }}
      RSA_PUBLIC: ${{ secrets.RSA_PUBLIC }}
      RSA_PRIVATE: ${{ secrets.RSA_PRIVATE }}
      EDAMAM_APP_ID: ${{ secrets.EDAMAM_APP_ID }}
      EDAMAM_APP_KEY: ${{ secrets.EDAMAM_APP_KEY }}
    services:
      postgres:
        image: postgres:latest

        ports:
          - 5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify